/**
 * Millennium Semiconductors' real, published distributor line card —
 * sourced from https://www.millenniumsemi.com/line-card/ (fetched
 * 2026-08-10). This is the client's actual authorized-brand network, not
 * invented data. It is intentionally kept separate from the `Manufacturer`
 * type used elsewhere in the app (src/types/product.ts), which is derived
 * strictly from products.json — most of these ~89 brands don't have SKUs
 * loaded into the prototype catalog yet, so they must not be wired into
 * the clickable, product-backed manufacturer directory (that would create
 * dead-end pages promising searchable inventory that doesn't exist).
 *
 * Where a brand here does overlap with a manufacturer already in the live
 * catalog (see crossReferenceLineCard in the Manufacturers screen), the UI
 * is allowed to link through to that manufacturer's real product page.
 * Everything else renders as a static, honestly-labeled "authorized brand"
 * chip — see the "Global Line Card" section on the Manufacturers screen.
 */
export const LINE_CARD_BRANDS: string[] = [
  'Megahunt',
  'IndieSemiC',
  'Next Biometrics',
  'ATP Electronics',
  'JonDeTech',
  'Shibaura',
  'MoMagic',
  'Rectron',
  'PARA LIGHT',
  'KDS',
  'Kemet',
  'Abracon',
  'Renesas',
  'XTX',
  'Raytac',
  'Hannstar',
  'Viitorsemi',
  'On-Bright',
  'PSA Inpaq Technology',
  'Thakor Electronics Limited',
  'Kyocera AVX',
  'Pulse Electronics',
  'Yangzhou Yangjie',
  'Wuxi Compul',
  'JJM',
  'Qixing',
  'Chogori',
  'Cyntec',
  'Linkcom',
  'Momentive',
  'Azoteq',
  'Lantronix',
  'Littelfuse',
  'Infineon',
  'Quectel',
  'Melexis',
  'Elmos',
  'Nuvoton',
  'Nordic',
  'MPS',
  'Rohm',
  'Semtech',
  'Taiwan Semiconductor',
  'Silan',
  'Tuya',
  'Winbond',
  'Bosch',
  'Digi',
  'UTC',
  'e-peas',
  'Panjit',
  'Everlight',
  'Truly',
  'Vango',
  'Avdisplay',
  'Sanken',
  'Inventronics',
  'Emis India',
  'Phison',
  'Holitech',
  'Omnivision',
  'Will Semi',
  'Nationstar',
  'Dominant',
  'Panasonic',
  'ASJ',
  'Delta',
  'Edison',
  'Yageo',
  'Chilisin',
  'Rubycon',
  'TDK',
  'Isabellenhutte',
  'Hornby Electronics',
  'Weidy',
  'SS-Magnet',
  'Sunon',
  'PSA Walsin Technology',
  'Ymin',
  'Fenghua',
  'Enfalion',
  'NDF',
  'Pchicon',
  'Ucon',
  'Laird Technologies',
  'Hongfa',
  'TE Connectivity',
  'GCT',
  'Conquer',
  'Hao Yueh',
];
