export const STORAGE_KEYS = {
  session: 'md.auth.session',
  registeredUsers: 'md.auth.users',
  cart: 'md.cart',
  wishlist: 'md.wishlist',
  compare: 'md.compare',
  recentlyViewed: 'md.recentlyViewed',
  productOverrides: 'md.products.overrides',
  orders: 'md.orders',
  addresses: 'md.addresses',
  hasSeenWelcome: 'md.hasSeenWelcome',
  governance: 'md.governance',
  designRequests: 'md.designRequests',
  sellerApplications: 'md.sellerApplications',
  rfqs: 'md.rfqs',
} as const;
